### ISSUE TITLE
Add a Coding Style Guides part

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/awesome-regex#1]

**Comment by huei90** [comment]
Is this the part you mentioned in CONTRIBUTING?

- Use the following format: [LIBRARY](LINK) - DESCRIPTION

**Comment by aloisdg** [comment]
I thought about a Regex Coding Style Guides. Is there a guide of best practices and a kind of norm to write a regex?

**Comment by huei90** [comment]
Looks like it's **Regular Expression Style Guides**. Not the code one. 

I didn't see any best practices for Regular Expression so far, only lots of tutorial and document.

Perhaps the style might be like this
use `\d` instead of `[0-9]`
some kind like that?

**Comment by aloisdg** [comment]
[A discussion on this topic](https://github.com/regexps/meta/issues/6)

**Comment by tunnckoCore** [comment]
@aloisdg we agreed there, it not make much sense to for some strict things. We will just do some scaffolders, project generators and boilerplates to allow faster adoption and development.

We just trying to follow only some naming convention and always return function that returns the regex. And that's really pretty enough when I rethink it.

And want to point it out again, the organization isn't only for Javascript. When I created the organization and ping first mentions of some persons I wanted and still wants to collect all regular expressions in one place and all around them - tools, services, websites, wikis, discussions.

Im very busy know, but to the end of the month I will start moving the project in some way. It also needs shares, tweets, website, twitter profile.

Thanks for the reference. Next time can ping me by username. :)

**Comment by huei90** [comment]
ping @tunnckoCore Thanks for your comment :+1:

**Comment by aloisdg** [comment]
I join @huei90 to thank you, @tunnckoCore , for the comment.
