### ISSUE TITLE
Should we add a "Tips and Tricks" part?

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/awesome-regex#10]
Hello,

I think it would be nice to add a "Tips and Tricks" part.
This part could contain this kind of resource :

- [Five Invaluable Techniques to Improve Regex Performance](https://www.loggly.com/blog/five-invaluable-techniques-to-improve-regex-performance/)

Any thoughts?

**Comment by huei90** [comment]
:+1: Yes, I think it should.

**Comment by aloisdg** [comment]
By the way, should I keep this clickbaity title?
