### ISSUE TITLE
Add Library

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/awesome-regex#18]
Hello,

[VerbalExpressions](https://github.com/VerbalExpressions) is a set of library to construct simply difficult regular expressions.
I don't know where should we put this.

I was thinking about adding a "Library" section for a long time. It make sens and there is a ton of content to add in it. Should we?

Any other idea?

**Comment by huei90** [comment]
Yes, this belongs to a new section "Library".

For the JSVervalExpressions

> VerbalExpressions is a JavaScript library that helps to construct difficult regular expressions.

**Comment by aloisdg** [comment]
@huei90 Can you create it?

**Comment by aloisdg** [comment]
I will do it.

**Comment by huei90** [comment]
sry @aloisdg :+1:

**Comment by aloisdg** [comment]
No problem.
