### ISSUE TITLE
Add Books and Articles section

### ISSUE THREAD

**Issue by quobit** [aloisdg/awesome-regex#23]
What do you think?

**Comment by aloisdg** [comment]
Why not. Can you create a PR with this vision? Which link would you move to it?

**Comment by quobit** [comment]
I think I'll create first the section and put some links to boks there. Maybe the 'Articles' part overlaps the Tips & Tricks section.

**Comment by aloisdg** [comment]
@quobit Maybe we could just rename this section "Article" and move regexlib somewhere else.

**Comment by quobit** [comment]
I've changed the subsection title but don't know where to move regexlib.

**Comment by aloisdg** [comment]
@quobit me neither. :smile: 

A list named "Collections"? I don't really know.

**Comment by quobit** [comment]
Good idea @aloisdg! I like "Collections"!

**Comment by quobit** [comment]
Done. Take a look @aloisdg

**Comment by aloisdg** [comment]
@quobit Looks good for me.
