### ISSUE TITLE
Additional Resources

### ISSUE THREAD

**Issue by Varunram** [aloisdg/awesome-regex#47]
Hi there! Amazing collection you have here! I created a very similar one independently and was wondering if I could merge it with yours. Its over at  https://github.com/Varunram/Awesome-Regex-Resources if you're interested. Thanks! 

CC @aloisdg @quobit

**Comment by aloisdg** [comment]
@Varunram of course ! Add every missing link in a PR. Thank you :)

**Comment by Varunram** [comment]
Closed via https://github.com/aloisdg/awesome-regex/commit/5555aa6ff437317b00a3a627fe8e429ae25a349d
