### ISSUE TITLE
awesome-regexp

### ISSUE THREAD

**Issue by huei90** [aloisdg/awesome-regex#5]
Sorry that I didn't got your page here =(

and create the another one 
https://github.com/huei90/awesome-regexp

Seems we have something can merge

**Comment by aloisdg** [comment]
Hello,

> Sorry that I didn't got your page here =(

No problem at all :)

> Seems we have something can merge

Sure. You build a nice list ! This one is older and get more star.
Are you ok to close yours and add all your link ?

By the way, I would love to invite you as a collaborator on this one. :)

**Comment by huei90** [comment]
Ok ! I will do it!

**Comment by huei90** [comment]
@aloisdg I think there is some problem on google this.

I have tried before
awesome regular expression, awesome regexp, awesome regex

Due to there are many name for regex, it's not easy for us to google this project =(

**Comment by aloisdg** [comment]
We are easy to find on [GitHub](https://github.com/search?utf8=%E2%9C%93&q=awesome+regex). I don't really care about Google for know. There are a lot of great resource out there. We will be visible in Google where we will be good enough. For now, let's grow.

**Comment by huei90** [comment]
sure, you are right.

**Comment by aloisdg** [comment]
Don't add something you didn't try before and you would not recommend absolutely. You seem motivated but it is just the beginning. Commit, push, have fun and remember : 

> With great power comes great responsibility

;)

**Comment by huei90** [comment]
Thanks @aloisdg I will suggest the one that I used before which is really useful.

**Comment by aloisdg** [comment]
Perfect and welcome aboard.

**Comment by n1trux** [comment]
@huei90 to find this stuff on Google, you could include a meaningful description or meta tags in the header.

In my awesome-sysadmin repo, I did it like this:

```
<!--
  Title: Awesome Sysadmin
  Description: A curated list of amazingly awesome open source sysadmin resources.
  Author: n1trux
  -->
```

Which is essentially an HTML comment. You could also just use real meta tags like so:

```
<meta name='keywords' content='regex, regular expressions, regexp'>
```

If you include that in the header, it won't be shown.

**Comment by aloisdg** [comment]
@n1trux Thank you for the comment. I create a new issue to discuss about general SEO. Feel free to continue this discussion at #9 . :)
