### ISSUE TITLE
Add new category benchmarks?

### ISSUE THREAD

**Issue by mariomka** [aloisdg/awesome-regex#50]
Before creating a pull request.

I guess Benchmarks category would be useful, some links:

http://lh3lh3.users.sourceforge.net/reb.shtml
http://sljit.sourceforge.net/regex_perf.html
https://github.com/mariomka/regex-benchmark (It's mine)

What do you think?

**Comment by aloisdg** [comment]
Nice idea

**Comment by Varunram** [comment]
Cool!
