### ISSUE TITLE
Is time to locate this to official awesome list

### ISSUE THREAD

**Issue by hueitan** [aloisdg/awesome-regex#53]
I think it's time for us to put this into [the official awesome list](https://github.com/sindresorhus/awesome) with the official logo [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)

**Comment by Varunram** [comment]
Done! https://github.com/sindresorhus/awesome/pull/1188

**Comment by aloisdg** [comment]
Well done
