### ISSUE TITLE
Add meta data for SEO

### ISSUE THREAD

**Issue by aloisdg** [aloisdg/awesome-regex#9]
Hello,

This is a [problem raised](https://github.com/aloisdg/awesome-regex/issues/5#issuecomment-117254653) by @huei90.
This project is findable in Google.

A [workaround proposed](https://github.com/aloisdg/awesome-regex/issues/5#issuecomment-117992028) by @n1trux is to add a small HTML comment at the top of the README.md. You can see is own implementation in his [awesome-sysadmin](https://raw.githubusercontent.com/n1trux/awesome-sysadmin/master/README.md) repo. For us, it could look like this :

```html
<!--
  Title: Awesome Regex
  Description: A curated list of amazingly awesome open source regex resources.
  Author: aloisdg
-->
```

As we dont need to focus on SEO right now, my first advice was to let it go. Since it is is just a small copy/paste, I think we should add it.

I created this to discuss on the Global SEO subject.

**Comment by n1trux** [comment]
another suggestion from me would be a meta tag, quote:

>In my awesome-sysadmin repo, I did it like this:

```
<!--
  Title: Awesome Sysadmin
  Description: A curated list of amazingly awesome open source sysadmin resources.
  Author: n1trux
  -->
```

> Which is essentially an HTML comment. You could also just use real meta tags like so:

```
<meta name='keywords' content='regex, regular expressions, regexp'>
```

> If you include that in the header, it won't be shown.

**Comment by huei90** [comment]
Cool! I don't know this tricks before :+1:

**Comment by huei90** [comment]
Until, GitHub introduce the SEO meta!
https://github.com/blog/2162-better-discoverability-for-github-pages-sites

**Comment by aloisdg** [comment]
Nice! @huei90 Can you make a quick PR?

**Comment by huei90** [comment]
This works only GitHub Pages. Let's wait for the README SEO meta. 🍻
